### ISSUE TITLE
How to test code that intentionally throws errors?

### ISSUE THREAD

**Issue by ncarchedi** [datacamp/testwhat#25]
I don't know how often this will be the case in the future, but certain parts of the R Functions course that Hadley and Charlotte are working on require the student to write functions that fail on certain conditions, then call their functions to check that they fail as intended. In other words, the purpose of the exercise is to cause an error.

This obviously doesn't play well with our current testing system since the solution code causes an error, so we've been commenting out the parts of these solution scripts that actually call the failing function and instead just ask the student to uncomment the code in the sample script. I think this is fine for now, but it may be a bit unnatural/confusing to students and I'm wondering if there's a better way.

Here are some examples:
https://campus.datacamp.com/courses/1008/2228?ex=2
https://campus.datacamp.com/courses/1008/2228?ex=3
https://campus.datacamp.com/courses/1008/2228?ex=9

**Comment by filipsch** [comment]
@ncarchedi There is no support for this yet, but shouldn't be too hard.

**Comment by ncarchedi** [comment]
@filipsch Great, thanks. We're hoping to beta test the functions course next week. Would be awesome if we had something by then, but I know you have your plate full at the moment!

**Comment by filipsch** [comment]
There's two parts to this problem:

- There should be a way to test if a function throws an error. Like `test_expression_output()` and `test_expression_result()`, you also want `test_expression_error()`, right?
- There should be a way to tell the system that you want the solution code to run an error on purpose. I'm not a fan of allowing this for all exercises on the platform for the sake of a couple of exercises, because you want to tell course authors when their solution doesn't run. What we could do, however, is adding a function to the RBackend so that you can specify in your SCT:

    *** =pec
    ```{r}
    code_throws_error()
    ```

So that RBackend knows about this and will not complain if the solution generates an error. 

The first bullet requires a change in `testwhat`, the second on in `RBackend`.

What do you think?

**Comment by ncarchedi** [comment]
@filipsch This is perfect. `test_expression_error()` + `code_throws_error()`. This is likely blocking release of the Writing Functions in R course, which is scheduled for release on 6/20. Thanks!
