### ISSUE TITLE
Unexpected error from test_output_contains()

### ISSUE THREAD

**Issue by tommyjee** [datacamp/testwhat#70]
@machow (@ncarchedi) Please see the SCTs corresponding to [this exercise](https://campus.datacamp.com/courses/1414/3379?ex=7) in Chapter 2 titled "Plotting just the UK over time". The link to the course on the teach app is [here](https://www.datacamp.com/teach/repositories/420/branches/master). 

![unspecified-3](https://cloud.githubusercontent.com/assets/8116732/19752932/e1e8489a-9bce-11e6-88c3-2b11f712253f.png)

For now, I commented out the `test_output_contains(by_year_country)` because that line throws an error saying "Did you print out `by_year_country` to the console?" even though it was printed. The `by_year_country` is a dataset that does not get altered in the progression of this exercise, so I have no idea why `test_output_contains()` is doing this.

**Comment by filipsch** [comment]
Hey @tommyjee, I discussed with @machow and looked into it.

For some obscure reason, the printout of `by_year_country` changes after the `filter` operation has happened (probably also some lazy magic behind the scenes). Boefre the `filter` operation, the printout is

```
Source: local data frame [4,744 x 4]
Groups: year [?]

    year                         country total percent_yes
   <dbl>                           <chr> <int>       <dbl>
1   1947                     Afghanistan    34   0.3823529
2   1947                       Argentina    38   0.5789474
3   1947                       Australia    38   0.5526316
4   1947                         Belarus    38   0.5000000
5   1947                         Belgium    38   0.6052632
6   1947 Bolivia, Plurinational State of    37   0.5945946
7   1947                          Brazil    38   0.6578947
8   1947                          Canada    38   0.6052632
9   1947                           Chile    38   0.6578947
10  1947                        Colombia    35   0.5428571
# ... with 4,734 more rows
```

After, it is

```
> by_year_country
Source: local data frame [4,744 x 4]
Groups: year [34]

    year                         country total percent_yes
   <dbl>                           <chr> <int>       <dbl>
1   1947                     Afghanistan    34   0.3823529
2   1947                       Argentina    38   0.5789474
3   1947                       Australia    38   0.5526316
4   1947                         Belarus    38   0.5000000
5   1947                         Belgium    38   0.6052632
6   1947 Bolivia, Plurinational State of    37   0.5945946
7   1947                          Brazil    38   0.6578947
8   1947                          Canada    38   0.6052632
9   1947                           Chile    38   0.6578947
10  1947                        Colombia    35   0.5428571
# ... with 4,734 more rows
```

(in the first printout, it is `Groups year [?]`, and the second printout `Groups: year [34]`.

It is this last printout that `test_output_contains()` will generate and look for in the student's output, but not find...

I suggest you use `check_output()` instead of `test_output_contains()`, to just check if the correct first line was printed out:

```r
ex() %>% check_output("Source: local data frame [4,744 x 4]", fixed = TRUE)
```

I checked, and this works.

@machow this funny little thing doesn't require any changes to `testwhat` IMO, so won't do a PR.
