### ISSUE TITLE
testing message output

### ISSUE THREAD

**Issue by machow** [datacamp/testwhat#72]
It looks like `test_output_contains` only has access to output piped to stdout, but `message()` directs to stderr.

In order to test message output, some possible solutions:

1. `test_output_contains` tests both normal output and messages
2. write a function called something like `test_message_contains`

### Example

*** =solution
```{r}
message("I am a message")
```

*** =sct
```{r}
test_output_contains("I am a message")
```

**Comment by filipsch** [comment]
`message()` creates a payload in the output list (accessible through `state$get("output_list")`) of type `r-message`.

The `test_output_contains()` logic is in `check_output.R`.

Actually, the helper function `convert_output_list()` already contains an `output_only` argument, that is `TRUE` when used with `test_output_contains()`. Would be a matter of adding an argument `output_only` to `check_output()` (and `test_output_contains()`, if you also want it to work for the 'old syntax'), that's `TRUE` by default, but can be user-specified.

**Comment by filipsch** [comment]
@machow, actually, this is already possible!

```
ex() %>% check_output("I am a message")
```

The above SCT will by default consider both normal output, as well as messages, warnings and errors. I'll do a small PR to make this `output_only` argument more explicit and controllable inside `check_output`. My first proposal, of adapting `check_output_expr()` (and `test_output_contains()`, which wraps around this), isn't really necessary, because these functions run an expression and then look at the resulting output and look for it in the output that the student generated. This means you'd basically have to use `test_output_contains("message(\"I am a message\")", output_only = FALSE)`. Simply using `check_output()` in this case is easier (it does not have a `test_` equivalent). I'll add the option to `test_output_contains()` and `check_output_expr()` anyways, just so that people are free to choose what to use.

cc @ncarchedi
