### ISSUE TITLE
check_output_expr behavior is confusing for errors

### ISSUE THREAD

**Issue by machow** [datacamp/testwhat#91]
From pairing w/ @richierocks. If you have an exercise with no code, and the following SCT

*** =sct
```{r}
ex() %>% check_output_expr("x")
```

The test will fail with feedback `Did your code produce the same output as x?`. It seems like it should either:

a) produce an SCT error for instructors

b) check that the error outputs are identical between student and solution

@filipsch thoughts?

**Comment by filipsch** [comment]
@machow yes totally agreed! I'm confused because I think this was in there at some point.

BTW, related but surprising. In `test-check-output.R`, there's tests that check for a message in the form `"Is the output of <code>print\\(123\\)</code> in your script"`, but that's no longer in the code..
I don't know why.

**Comment by machow** [comment]
Sounds good! I think that's basically the message that was returned. Sorry I should formatted it... 

`Did your code produce the same output as <code>x</code>?`

**Comment by filipsch** [comment]
If you look at the code, that message is not generated anywhere, it seems. That's the confusing thing. I might be missing something.

**Comment by filipsch** [comment]
I was working on a the `post_exercise_code` branch, and there I saw that, as I thought, the tests for `check_output_expr` were broken. Extremely strange. Anyways, that's not the real issue here.

Basically, you want a more informative error if the CD users `check_output_expr()` with a code string that either does not generate an output or generates an error when executed, right?

**Comment by machow** [comment]
Either that or compares the errors. But I think what you suggested, generating an error for CDs would be simpler (and later we could add an error argument if they really need the option).

**Comment by machow** [comment]
hmm... it appears that the expression is evaluated in the student environment ([code here](https://github.com/datacamp/testwhat/blob/master/R/check-output.R#L89)). It should be the solution environment, right?

**Comment by filipsch** [comment]
Nah, don't think so. You, for example, want to make sure they printed a variable that they created, which is not necessarily the exact same one as the one in the solution environment.

**Comment by machow** [comment]
Okay, I see--that behavior I was thinking about is already implemented using

```
ex() %>% check_expr('x') %>% check_output() %>% check_equal()
```

**Comment by machow** [comment]
Okay, apparently the original issue as described is not a bug! I'll update the docs to be clear that this SCT is to check that the student produced output, using an expression that runs in **their** environment. (e.g. one use case might be letting the student assign any value to a variable `x`, but making sure they output that value in some what).

**Comment by machow** [comment]
looks like it was done in this commit: a283c04a9c30d425730b72706044fe66deabd6af
